/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppFaultsRouteImport } from './routes/app.faults'
import { Route as AppChecklistsTemplateIdRouteImport } from './routes/app.checklists.$templateId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFaultsRoute = AppFaultsRouteImport.update({
  id: '/faults',
  path: '/faults',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistsTemplateIdRoute = AppChecklistsTemplateIdRouteImport.update({
  id: '/checklists/$templateId',
  path: '/checklists/$templateId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/faults': typeof AppFaultsRoute
  '/app/': typeof AppIndexRoute
  '/app/checklists/$templateId': typeof AppChecklistsTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/faults': typeof AppFaultsRoute
  '/app': typeof AppIndexRoute
  '/app/checklists/$templateId': typeof AppChecklistsTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/faults': typeof AppFaultsRoute
  '/app/': typeof AppIndexRoute
  '/app/checklists/$templateId': typeof AppChecklistsTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/faults'
    | '/app/'
    | '/app/checklists/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/app/faults' | '/app' | '/app/checklists/$templateId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/faults'
    | '/app/'
    | '/app/checklists/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faults': {
      id: '/app/faults'
      path: '/faults'
      fullPath: '/app/faults'
      preLoaderRoute: typeof AppFaultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checklists/$templateId': {
      id: '/app/checklists/$templateId'
      path: '/checklists/$templateId'
      fullPath: '/app/checklists/$templateId'
      preLoaderRoute: typeof AppChecklistsTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFaultsRoute: typeof AppFaultsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChecklistsTemplateIdRoute: typeof AppChecklistsTemplateIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFaultsRoute: AppFaultsRoute,
  AppIndexRoute: AppIndexRoute,
  AppChecklistsTemplateIdRoute: AppChecklistsTemplateIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
